FROM node:20

ENV MONGO_URL=mongodb://devops-db:27017
ENV DB_NAME=application
ENV PORT=3000

WORKDIR /application

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]