version: '1'
name: devops-project
services:
  messagebus:
    container_name: devops-messagebus
    image: rabbitmq:latest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
  application:
    container_name: devops-application
    build: 
      context: ./application
      dockerfile: dockerfile.prod
    ports: 
      - 3001:3001
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      database:
        condition: service_started
      messagebus:
        condition: service_healthy
    environment:
      - PORT=3001
      - MESSAGE_QUEUE=amqp://devops-messagebus
      - MONGO_URL=mongodb://admin:admin@database:27017
    volumes:
      - ./application:/usr/src/app
      - /usr/src/app/node_modules
  logging:
    container_name: devops-logging
    build: 
      context: ./logging
      dockerfile: dockerfile.prod
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      logdatabase:
        condition: service_started
      messagebus:
        condition: service_healthy
    environment:
      - MESSAGE_QUEUE=amqp://devops-messagebus
      - MONGO_URL=mongodb://admin:admin@logdatabase:27017
  database:
    container_name: database
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=devops-db
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
       - app_data:/data/db
  logdatabase:
    container_name: logdatabase
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=devops-logs
    expose:
      - 27017
    volumes:
       - log_data:/data/db
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  grafana:
    build: ./grafana
    ports:
      - 3000:3000
  db-exporter:
    container_name: db-exporter
    image: bitnami/mongodb-exporter:latest
    environment:
      - MONGODB_URI=mongodb://admin:admin@database:27017
      - MONGODB_EXPORTER_ENABLE_ADMIN_API=true
    ports:
      - 9216:9216
volumes:
  app_data:
  log_data:
  prometheus_data: