version: '1'
name: devops-project
services:
  messagebus:
    container_name: devops-messagebus
    image: rabbitmq:latest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
  application:
    container_name: devops-application
    build: 
      context: ./application
      dockerfile: dockerfile.prod
    ports: 
      - 3000:3000
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      database:
        condition: service_started
      messagebus:
        condition: service_healthy
    environment:
      - MESSAGE_QUEUE=amqp://devops-messagebus
      - MONGO_URL=mongodb://admin:admin@devops-db:27017
  logging:
    container_name: devops-logging
    build: 
      context: ./logging
      dockerfile: dockerfile.prod
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      logdatabase:
        condition: service_started
      messagebus:
        condition: service_healthy
    environment:
      - MESSAGE_QUEUE=amqp://devops-messagebus
      - MONGO_URL=mongodb://admin:admin@devops-logs:27017
  database:
    container_name: devops-db
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=devops-db
    expose:
      - 27017
    volumes:
       - app_data:/data/db
  logdatabase:
    container_name: devops-logs
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=devops-logs
    expose:
      - 27017
    volumes:
       - log_data:/data/db
volumes:
  app_data:
  log_data: