FROM node:20

ENV MONGO_URL=mongodb://localhost:27017
ENV DB_NAME=logging
ENV MESSAGE_QUEUE=amqp://localhost

WORKDIR /logger

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]