FROM node:20

ENV MONGO_URL=mongodb://devops-logs:27018
ENV DB_NAME=logging
ENV MESSAGE_QUEUE=amqp://devops-messagebus

WORKDIR /logger

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "start"]