groups:
  - name: DemoAlerts
    rules:
      - alert: 'On app down'
        expr: up{job="application"} < 1
        for: 30s
      - alert: HighRequestRate
        expr: rate(http_requests_total{job="application"}[5m]) > 10
        for: 1m
