global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - 'alert.yml'

scrape_configs:
  - job_name: 'application'
    static_configs:
      - targets: ['application:3001']
  - job_name: 'db-exporter'
    static_configs:
      - targets: ['db-exporter:9216']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
