name: Logging CI
on:
  push:
    paths:
      - 'logging/**'
  pull_request:
    branches:
      - main
jobs:
  coverage:
    name: Tests and linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./logging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
        working-directory: ./logging
      - name: Run tests
        uses: ArtiomTr/jest-coverage-report-action@v2.3.0
        with:
          working-directory: ./logging
